# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DBIx-MoCo-Pageset
version:      0.01
author: 
  - syushi matsumoto <matsumoto@alink.co.jp>
build_requires: 
  Test::More: 0
version_from: lib/DBIx/MoCo/Pageset.pm
installdirs:  site
requires:
  DBIx::MoCo: 0
  Data::Pageset: 1.02

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17

